function bucket = read_bucket(socket)

    meta = read_bucket_meta(socket);
    data      = read_bundle(socket, meta.data, meta.data_stats);
    ref       = read_bundle(socket, meta.ref, meta.ref_stats);
    waveforms = read_waveform(socket, meta.waveform);
    
    bucket = gadgetron.types.Bucket(data, ref, waveforms);    
end

function meta = read_bucket_meta(socket)

    bytes = read(socket, 104, 'uint8');
    
    meta.data.count               = typecast(bytes(1:8), 'uint64'); 
    meta.data.nbytes.header       = typecast(bytes(9:16), 'uint64');
    meta.data.nbytes.data         = typecast(bytes(17:24), 'uint64');
    meta.data.nbytes.trajectory   = typecast(bytes(25:32), 'uint64');
    
    meta.ref.count                = typecast(bytes(33:40), 'uint64');
    meta.ref.nbytes.header        = typecast(bytes(41:48), 'uint64');
    meta.ref.nbytes.data          = typecast(bytes(49:56), 'uint64');
    meta.ref.nbytes.trajectory    = typecast(bytes(57:64), 'uint64');
    
    meta.data_stats.nbytes        = typecast(bytes(65:72), 'uint64');
    meta.ref_stats.nbytes         = typecast(bytes(73:80), 'uint64');
    
    meta.waveform.count           = typecast(bytes(81:88), 'uint64');
    meta.waveform.nbytes.header   = typecast(bytes(89:96), 'uint64');
    meta.waveform.nbytes.data     = typecast(bytes(97:104), 'uint64');
    
    meta.nbytes_total = ...
        meta.data.nbytes.header + ...
        meta.data.nbytes.data + ...
        meta.data.nbytes.trajectory + ...
        meta.data_stats.nbytes + ...
        meta.ref.nbytes.header + ...
        meta.ref.nbytes.data + ...
        meta.ref.nbytes.trajectory + ...
        meta.ref_stats.nbytes + ...
        meta.waveform.nbytes.header + ...
        meta.waveform.nbytes.data;
end

function bundle = read_bundle(socket, meta, stats)

    bundle.count = meta.count;

    bundle.header = ...
        gadgetron.external.readers.decode_acquisition_headers( ...
            read(socket, meta.nbytes.header, 'uint8'), ...
            bundle.count ...
        );
    
    bundle.trajectory = ...
        typecast( ...
            read(socket, meta.nbytes.trajectory, 'uint8'), ...
            'single' ...
        );                
    
    bundle.data = ...
        gadgetron.external.readers.as_interleaved_complex( ...
            typecast( ...
                read(socket, meta.nbytes.data, 'uint8'), ...
                'single' ...
            ) ...
        );        
    
    bundle.stats = ...
        gadgetron.types.lazy.AcquisitionStats( ...
            read(socket, stats.nbytes, 'uint8') ...
        );
    
    if (bundle.count == 0), return; end
    
    bundle.trajectory = reshape( ...
        bundle.trajectory, ...
        bundle.header.trajectory_dimensions(1), ...
        bundle.header.number_of_samples(1), ...
        meta.count ...
    );
    
    bundle.data = reshape( ...
        bundle.data, ...
        bundle.header.number_of_samples(1), ...
        bundle.header.active_channels(1), ...
        meta.count ...
    );
end

function waveforms = read_waveform(socket, meta)

    headers = ...
        gadgetron.external.readers.decode_waveform_headers( ...
            read(socket, meta.nbytes.header, 'uint8'), ...
            meta.count ...
        );
    
    data = ...
        typecast( ...
            read(socket, meta.nbytes.data, 'uint8'), ...
            'int32' ...
        );        
    
    % Split the data array into individual waveform data.
    data = mat2cell(data, headers.number_of_samples .* headers.channels);     

    function waveform = create_waveform(index)
        waveform_header = structfun(@(array) array(:, index), headers, 'UniformOutput', false);
        waveform_data = reshape(data{index}, [waveform_header.number_of_samples, waveform_header.channels]);        
        waveform = gadgetron.types.Waveform(waveform_header, waveform_data);                
    end

    waveforms = arrayfun(@create_waveform, 1:meta.count);
end
